/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-06-30 03:01:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.sql.*;
import java.util.*;
import com.wy.domain.AfficheForm;
import com.wy.domain.GoodsForm;
import com.wy.domain.MemberForm;
import com.wy.domain.LinkForm;

public final class fg_002dleft_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.wy.domain.GoodsForm");
    _jspx_imports_classes.add("com.wy.domain.LinkForm");
    _jspx_imports_classes.add("com.wy.domain.MemberForm");
    _jspx_imports_classes.add("com.wy.domain.AfficheForm");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<title>无标题文档</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function checkEmpty(form){\r\n");
      out.write("for(i=0;i<form.length;i++){\r\n");
      out.write("if(form.elements[i].value==\"\"){\r\n");
      out.write("alert(\"表单信息不能为空\");\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function quit() {\r\n");
      out.write("  if(confirm(\"没有要买的东西了吗？\")){\r\n");
      out.write("    window.location.href=\"loginOut.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.wy.dao.AfficheDao affiche = null;
      affiche = (com.wy.dao.AfficheDao) _jspx_page_context.getAttribute("affiche", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (affiche == null){
        affiche = new com.wy.dao.AfficheDao();
        _jspx_page_context.setAttribute("affiche", affiche, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.wy.dao.GoodsDao goods = null;
      goods = (com.wy.dao.GoodsDao) _jspx_page_context.getAttribute("goods", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (goods == null){
        goods = new com.wy.dao.GoodsDao();
        _jspx_page_context.setAttribute("goods", goods, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.wy.dao.LinkDao linkdao = null;
      linkdao = (com.wy.dao.LinkDao) _jspx_page_context.getAttribute("linkdao", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (linkdao == null){
        linkdao = new com.wy.dao.LinkDao();
        _jspx_page_context.setAttribute("linkdao", linkdao, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      com.wy.tool.CountTime countTime = null;
      countTime = (com.wy.tool.CountTime) _jspx_page_context.getAttribute("countTime", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (countTime == null){
        countTime = new com.wy.tool.CountTime();
        _jspx_page_context.setAttribute("countTime", countTime, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
List afficheList=(List)affiche.selectAffiche();
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!--左侧01-->\r\n");
      out.write("\t");
if(session.getAttribute("form")==null){
      out.write("\t\t\r\n");
      out.write("\t<table width=\"100%\" height=\"138\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/fg_left01.jpg\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td valign=\"top\"><table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t <tr>\r\n");
      out.write("            <td height=\"16\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <form name=\"form\" method=\"post\" action=\"memberAction.do?action=1\" onSubmit=\"return checkEmpty(form)\">\r\n");
      out.write("          <table width=\"185\" border=\"0\" align=\"center\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"60\" height=\"25\">用户名：</td>\r\n");
      out.write("              <td width=\"115\"> <input name=\"name\" type=\"text\" size=\"17\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td height=\"25\">密&nbsp;&nbsp;码：</td>\r\n");
      out.write("              <td><input name=\"password\" type=\"password\" size=\"17\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("              <td height=\"26\"><input type=\"image\" class=\"input1\"  src=\"image/fg-land.gif\" width=\"51\" height=\"20\"></td>\r\n");
      out.write("              <td height=\"26\">  &nbsp;&nbsp;<a href=\"fg-memberRegister.jsp\">注册</a>&nbsp;&nbsp;<a href=\"fg-One.jsp\">找回密码？</a></td>\r\n");
      out.write("\t\t\t </tr>\t  \r\n");
      out.write("          </table>\r\n");
      out.write("\t\t  </form>\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\t");
}else{
	   MemberForm form=(MemberForm)session.getAttribute("form");
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table width=\"100%\" height=\"138\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/fg_left01.jpg\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td valign=\"top\"><table width=\"100%\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("\t\t <tr>\r\n");
      out.write("            <td height=\"30\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("       \r\n");
      out.write("          <table width=\"167\" border=\"0\" align=\"center\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"161\" height=\"25\"><font color=\"#FB6801\">");
      out.print(form.getName());
      out.write(",</font>欢迎回来</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td height=\"25\">");
      out.print(countTime.currentlyTime());
      out.write("</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("\t\t\t <tr>\r\n");
      out.write("              <td height=\"25\" >会员姓名：");
      out.print(form.getReallyName());
      out.write("</td>\r\n");
      out.write("              </tr>\t \r\n");
      out.write("\t\t\t  <tr>\r\n");
      out.write("              <td height=\"20\" align=\"right\" valign=\"middle\"><a href=\"javascript:quit()\">安全退出</a></td>\r\n");
      out.write("              </tr>\t\r\n");
      out.write("          </table>\r\n");
      out.write("\t  </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t<!--左侧02-->\t\t\r\n");
      out.write("        <table width=\"100%\" height=\"194\" border=\"0\" background=\"image/fg_left02.jpg\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td valign=\"top\"><table width=\"150\" border=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"32\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("              <table width=\"179\" border=\"0\" align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=\"171\" height=\"143\">\r\n");
      out.write("\t\t\t\t  <marquee direction=\"up\" height=\"114\" onmouseout=\"this.start()\" \r\n");
      out.write("             onmouseover=\"this.stop()\" scrollAmount=\"1\" scrollDelay=\"1\">\t  \r\n");
      out.write("\t\t            ");

                      for(int i=0;i<afficheList.size();i++){
                        AfficheForm afficheForm=(AfficheForm)afficheList.get(i);
                        
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img src=\"image/sign.gif\">&nbsp;<a href=\"#\" onClick=\"window.open('fg-afficheSelect.jsp?id=");
      out.print(afficheForm.getId());
      out.write("','','width=500,height=400');\">");
      out.print(afficheForm.getName());
      out.write("</a><br><br>\r\n");
      out.write("\t\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("            </marquee>\t\t\t      </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\t\r\n");
      out.write("\t    <table width=\"100%\" height=\"193\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/fg_left03.jpg\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td valign=\"top\"><table width=\"194\" border=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"40\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>          \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            ");

             List goodsList =goods.selectGoodsNumber();
             int number=goodsList.size();
           if(number>7){
             number=7;
           }
             for(int account=0;account<number;account++){
             GoodsForm form=(GoodsForm)goodsList.get(account);
             
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  <table width=\"178\" height=\"19\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/fg_left04.jpg\">\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t    <td width=\"14\"></td>\r\n");
      out.write("                <td width=\"164\"><a href=\"bg-sellResult.jsp?id=");
      out.print(form.getId());
      out.write("&account=");
      out.print(account+1);
      out.write('"');
      out.write('>');
      out.print(account+1);
      out.write("&nbsp;&nbsp;");
      out.print(form.getName());
      out.write("</a></td>\r\n");
      out.write("\t\t\t\t</tr>   \r\n");
      out.write("            </table>\t\t\t\t\r\n");
      out.write("\t\t\t");
}
      out.write("\t</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("\t    <table width=\"207\" height=\"181\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"image/fg_left05.jpg\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td valign=\"top\"><table width=\"173\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"35\">&nbsp;</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("              <table width=\"186\" align=\"center\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td height=\"38\">\r\n");
      out.write("\t\t\t\t  <MARQUEE direction=\"up\" height=\"114\" onmouseout=\"this.start()\" \r\n");
      out.write("             onmouseover=\"this.stop()\" scrollAmount=\"1\" scrollDelay=\"1\">\t  \r\n");
      out.write("\t\t            ");

		              List linkList=(List)linkdao.selectLink();
                      for(int i=0;i<linkList.size();i++){
                      LinkForm linkForm=(LinkForm)linkList.get(i);
                      
      out.write("\r\n");
      out.write("\t\t\t\t\t<img src=\"image/sign1.gif\">&nbsp; <a href=\"");
      out.print(linkForm.getLinkAddress());
      out.write("\" target=\"_blank\">");
      out.print(linkForm.getLinkName());
      out.write("</a><br><br>\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("            </marquee>\t\t\t\t </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
