/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2016-06-30 03:01:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import com.wy.domain.GoodsForm;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.wy.domain.GoodsForm");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      com.wy.dao.GoodsDao newGood = null;
      newGood = (com.wy.dao.GoodsDao) _jspx_page_context.getAttribute("newGood", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (newGood == null){
        newGood = new com.wy.dao.GoodsDao();
        _jspx_page_context.setAttribute("newGood", newGood, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
List nowList =newGood.selectMark(Integer.valueOf("0"));
      out.write('\r');
      out.write('\n');
List freeList =newGood.selectMark(Integer.valueOf("1"));
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<title>电子商城</title>\r\n");
      out.write("</head>\r\n");
      out.write(" <link href=\"css/css.css\" rel=\"stylesheet\" type=\"text/css\"> \r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fg-top.jsp", out, true);
      out.write("\r\n");
      out.write("<table width=\"766\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"207\" valign=\"top\" bgcolor=\"#F5F5F5\">\r\n");
      out.write("    <!--左侧01-->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fg-left.jsp", out, true);
      out.write("</td>\r\n");
      out.write("    <td width=\"559\" valign=\"top\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("    <!--右侧01-->\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fg-goodSorts.jsp", out, true);
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div align=\"center\">\r\n");
      out.write("        ");
if(session.getAttribute("form")!=null){
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <img src=\"image/fg_right02.jpg\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#FFFFFF\" bordercolorlight=\"#FFFFFF\" bordercolordark=\"#819BBC\">\r\n");
      out.write("        <tr> \r\n");
      out.write("\t\t  ");

              int free=2;
              if(freeList.size()<2){
              free=freeList.size();
              }

              for(int i=0;i<free;i++)
              {
                GoodsForm newGoods=(GoodsForm)freeList.get(i);
                
      out.write("\r\n");
      out.write("            <td valign=\"top\">\t\t\t<table width=\"257\" height=\"136\" border=\"1\" align=\"center\" cellpadding=\"1\" cellspacing=\"1\" bordercolor=\"#FFFFFF\" bgcolor=\"#999999\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"33%\" height=\"80\" rowspan=\"5\" bgcolor=\"#FFFFFF\"><input name=\"pricture");
      out.print(i);
      out.write("\" type=\"image\" src=\"");
      out.print(newGoods.getPriture());
      out.write("\" width=\"140\" height=\"126\"></td>\r\n");
      out.write("                <td width=\"67%\" height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\">");
      out.print(newGoods.getName());
      out.write("</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\" style=\"text-decoration:line-through;color:#910402\">原价：");
      out.print(newGoods.getNowPrice());
      out.write("元</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\"><font color=\"#F14D83\">现价：");
      out.print(newGoods.getFreePrice());
      out.write("元</font></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"20\" bgcolor=\"#FFFFFF\"><div align=\"center\">");
      out.print(newGoods.getIntroduce());
      out.write("</div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"13\" bgcolor=\"#FFFFFF\"><div align=\"center\" class=\"linkBlack\"><a href=\"#\" onClick=\"window.open('goodsAction.do?action=16&id=");
      out.print(newGoods.getId());
      out.write("','','width=500,height=200');\">查看详细内容</a></div></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("        </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    <img src=\"image/fg_right01.jpg\">\r\n");
      out.write("</div>\r\n");
      out.write("<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    \r\n");
      out.write("          <tr>\r\n");
      out.write("            <td height=\"215\" valign=\"top\">\r\n");
      out.write("\t\t\t");

              int now=5;
              if(nowList.size()<5){
              now=nowList.size();
              }
             if(session.getAttribute("form")!=null){
			 now=3;
             }
              for(int i=0;i<now;i++)
              {
                GoodsForm newGoods=(GoodsForm)nowList.get(i);
                
      out.write("<table width=\"100%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>\t\t\t\t<table width=\"99%\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#CCCCCC\"   >\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td height=\"150\" bordercolor=\"#666666\" >\r\n");
      out.write("                      <table width=\"96%\"  border=\"1\" align=\"center\" cellpadding=\"1\" cellspacing=\"1\" bordercolor=\"#FFFFFF\" bgcolor=\"#CCCCCC\" >\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td width=\"36%\" rowspan=\"4\" bgcolor=\"#FFFFFF\"><div align=\"center\">\r\n");
      out.write("                              <input name=\"pricture");
      out.print(i);
      out.write("\" type=\"image\" src=\"");
      out.print(newGoods.getPriture());
      out.write("\" width=\"110\" height=\"100\">\r\n");
      out.write("                          </div></td>\r\n");
      out.write("                          <td width=\"64%\" bgcolor=\"#FFFFFF\"><div align=\"center\">");
      out.print(newGoods.getName());
      out.write("</div></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td bgcolor=\"#FFFFFF\"><div align=\"center\"><font color=\"#F14D83\">单价：");
      out.print(newGoods.getNowPrice());
      out.write("元</font></div></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td bgcolor=\"#FFFFFF\"><div align=\"center\">");
      out.print(newGoods.getIntroduce());
      out.write("</div></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td  bgcolor=\"#FFFFFF\" class=\"linkBlack\"  align=\"center\">\r\n");
      out.write("                              ");
if(session.getAttribute("form")!=null||session.getAttribute("id")!=null){
      out.write("\r\n");
      out.write("                              <a href=\"#\" onClick=\"window.open('goodsAction.do?action=16&id=");
      out.print(newGoods.getId());
      out.write("','','width=500,height=200');\">查看详细内容</a>\r\n");
      out.write("                              ");
}else{
      out.write("\r\n");
      out.write("                           登录后才能购买</td>\r\n");
      out.write("                          ");
}
      out.write("\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t       \r\n");
      out.write("          </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fg-down.jsp", out, true);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
